### ISSUE TITLE
BuildContent not working correctly

### ISSUE THREAD

**Issue by gmoita** [vertigo17/Cerberus#615]
Cerberus Version : 1.1.3-SNAPSHOT

When using the new BuildContent page, several things are not working correctly (screenshot attached):
1) Documentation not available
2) buttonLoadPending does not load the pending entries (neither fills the filter to be used)
3) action buttons are not shown
4) when using button_create, Build and Revision fields are not filled with the information from the filters (have to be filled each time a new entry is needed)
![buildcontent page is not correct](https://cloud.githubusercontent.com/assets/5640464/10588201/c9c4b51c-769c-11e5-9546-a3becfc93a47.jpg)

**Comment by gmoita** [comment]
Also, information is not shown correctly (very small columns) on the revision content list, especially link, subject and Owner information

**Comment by corentindms** [comment]
For the documentation, logging out and relogging in should do the trick

**Comment by gmoita** [comment]
Correct, I confirm

**Comment by gmoita** [comment]
Also for the buttons.
For the remaining, is is the same.

**Comment by afnogueira** [comment]
Related to issue #598

**Comment by vertigo17** [comment]
That should now be fixed with latest comit
Please validate and close the issue.

**Comment by gmoita** [comment]
Still not seeing the full information on the revision content list, especially link, subject and Owner information, as seen previously.
Link is not critical, but subject and owner description are.
To mantain it like this, I would like to mark this issue as an enhancement.

**Comment by gmoita** [comment]
When trying to use button "Load", after selecting build and revision, I get the error:
"ERROR - An unexpected error occured, the servlet may not be available. Please check if your session is still active"

**Comment by gmoita** [comment]
Sorry, might have been related to new deploy running at the same time.
No more option to see the content of all releases for one build (all revisions).

**Comment by vertigo17** [comment]
If I sumarize the pending subject out of your last comments :
1/ Optimise  columns size in order to better see the content.
2/ Allow to select ALL on Revision.
Correct ?

**Comment by vertigo17** [comment]
Both issues should be fixed now.
Please confirm.

**Comment by gmoita** [comment]
Deployed in PROD and working.
