### ISSUE TITLE
What happened to DataLib?

### ISSUE THREAD

**Issue by ruirpr** [vertigo17/Cerberus#653]
I've noticed some strage behaviours: 
- a test with a property getFromDataLib that used to work, does not work anymore;
- when editing the test the property changes to getFromTestData and getFromDataLib dissapeared;
- when going to Data->TestDataLib the error "An unexpected problem occurred. Unable to retrieve - data!" is shown;

Also, when going to Data -> TestData the menus change and there are missing links;

Please advise.

**Comment by vertigo17** [comment]
Rui,

I am not sure I understand but in order to clarify.
getFromDataLib is still in beta mode. If you want to use it please provide getFromDataLib_BETA (at the bottom of the combo).
I changed test case PDP mini PDP multi PDP / 0413A to point to getFromDataLib_BETA so it should fix the issue for that test, if you got others, please update them to getFromDataLib_BETA.

getFromTestData should still work as no changes were done on it recently.

I will check later the error on TestDataLib that seems to be linked with wrong date data format.

The Beta options are indeed not available on the old menus. I will also try to add them.

**Comment by vertigo17** [comment]
I also corrected PDP mini PDP multi PDP / 0412A to getFromDataLib_BETA.

**Comment by vertigo17** [comment]
All should be fixed in QA. Please confirm and reopen if necessary.

**Comment by mbessa** [comment]
Hello,

This problem is still present and we are unable to run the testcases that use getFromDataLib_BETA, for instance in PDP mini PDP multi PDP - 0413A even with the change you made to use "getFromDataLib_BETA", when running TC, this output is returned:
"Failed to execute because inner property 'URL_PRODUCT'  accesses invalid test data library entries: [PRODUCT]. "

If we try to see the data libraries in  "/Cerberus/TestDataLib.jsp" we received none and a error popup, but if we try to create another with the same options we received a error informing that already exists.

Can you check this please?

Thanks

**Comment by vertigo17** [comment]
I anticipated the SQL in order to correct the data allowing you to check the definition of the Datalib.
If the definition of datalib is correct and you still have the issue, please reopen the issue.
