### ISSUE TITLE
No build and no revision available on EditBuildContent

### ISSUE THREAD

**Issue by gmoita** [vertigo17/Cerberus#654]
Cerberus Version : 1.1.3-SNAPSHOT

When editing build revision content (from Load Pending build filter), we do not have any build or revision available for selection.
![no build revision information](https://cloud.githubusercontent.com/assets/5640464/11930725/04627ed0-a7de-11e5-9956-f69a104eada5.jpg)

**Comment by gmoita** [comment]
Please fix it asap.

**Comment by corentindms** [comment]
Should be fixed now

**Comment by gmoita** [comment]
But for already existing build content, it does not load any build and revision, always shows NONE on both.
Not fixed.

**Comment by corentindms** [comment]
build and revision were loaded but not pre-selected. Fixed it too.

**Comment by gmoita** [comment]
Confirmed ok and deployed in PROD.
